BEGIN;

-- Organizations: add contact_name and allow demo UI statuses.
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS contact_name TEXT NULL;

ALTER TABLE organizations
  DROP CONSTRAINT IF EXISTS organizations_status_check;
ALTER TABLE organizations
  ADD CONSTRAINT organizations_status_check
  CHECK (status IN ('pending','active','disabled','approved','rejected','inactive'));

-- Users: allow super_admin role used by current UI/API.
ALTER TABLE users
  DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users
  ADD CONSTRAINT users_role_check
  CHECK (role IN ('super_admin','admin','partner'));

-- Events: keep current values and persist denial metadata.
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS admin_comment TEXT NULL,
  ADD COLUMN IF NOT EXISTS reviewed_by_user_id BIGINT NULL REFERENCES users(user_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ NULL;

ALTER TABLE events
  DROP CONSTRAINT IF EXISTS events_status_check;
ALTER TABLE events
  ADD CONSTRAINT events_status_check
  CHECK (status IN ('pending','approved','denied','rejected'));

-- Event revisions: allow denied status for consistency with current UI labels.
ALTER TABLE event_revisions
  DROP CONSTRAINT IF EXISTS event_revisions_status_check;
ALTER TABLE event_revisions
  ADD CONSTRAINT event_revisions_status_check
  CHECK (status IN ('pending','approved','denied','rejected'));

-- Invitations: persist invite tokens generated by admin flow.
CREATE TABLE IF NOT EXISTS invitations (
  invitation_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  token          TEXT NOT NULL UNIQUE,
  role           TEXT NOT NULL CHECK (role IN ('super_admin','admin')),
  expires_at     TIMESTAMPTZ NOT NULL,
  consumed_at    TIMESTAMPTZ NULL,
  created_by_user_id BIGINT NULL REFERENCES users(user_id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_exp ON invitations(expires_at);

COMMIT;
