export const mockUsers = [
	{ user_id: 1, email: 'superAdmin@stemact.org', role: 'super_admin', org_name: null },
	{ user_id: 2, email: 'admin@stemact.org',      role: 'admin',       org_name: null },
	{ user_id: 3, email: 'stem@yale.edu',           role: 'partner',     org_name: 'Yale STEM Outreach' },
	{ user_id: 4, email: 'events@ctsci.org',        role: 'partner',     org_name: 'CT Science Center' },
	{ user_id: 5, email: 'mfrank@wilbur.edu',       role: 'partner',     org_name: 'Wilbur Elementary School' },
];

export const mockOrganizations = [
	{ org_id: 1, org_name: 'Yale STEM Outreach',       contact_name: 'Dr. Emily Chen',    contact_email: 'stem@yale.edu',       contact_phone: '203-555-0101', status: 'active' },
	{ org_id: 2, org_name: 'CT Science Center',         contact_name: 'James Kowalski',    contact_email: 'events@ctsci.org',    contact_phone: '860-555-0202', status: 'active' },
	{ org_id: 3, org_name: 'Wilbur Elementary School',  contact_name: 'Maria Frank',       contact_email: 'mfrank@wilbur.edu',   contact_phone: '203-555-0303', status: 'active' },
	{ org_id: 4, org_name: 'New Haven Public Library',  contact_name: 'Thomas Rivera',     contact_email: 'programs@nhpl.org',   contact_phone: '203-555-0404', status: 'pending' },
];

export const mockEvents = [
	{
		event_id: 1,
		org_id: 1,
		org_name: 'Yale STEM Outreach',
		title: 'Robotics Workshop for Teens',
		description: 'Hands-on workshop teaching students to build and program robots using Arduino kits.',
		start_datetime: '2026-03-15T10:00:00.000Z',
		end_datetime:   '2026-03-15T14:00:00.000Z',
		address: '15 Prospect St',
		city: 'New Haven',
		county: 'New Haven',
		audience: 'Ages 13-18',
		cost: '0.00',
		event_link: 'https://yale.edu/stem-robotics',
		contact_email: 'stem@yale.edu',
		status: 'pending',
		admin_comment: null,
		submitted_at: '2026-02-10T09:00:00.000Z',
	},
	{
		event_id: 2,
		org_id: 1,
		org_name: 'Yale STEM Outreach',
		title: 'Women in STEM Panel',
		description: 'Panel discussion featuring women in various STEM fields sharing their career journeys.',
		start_datetime: '2026-03-22T18:00:00.000Z',
		end_datetime:   '2026-03-22T20:00:00.000Z',
		address: '150 York St',
		city: 'New Haven',
		county: 'New Haven',
		audience: 'High School & College Students',
		cost: '0.00',
		event_link: 'https://yale.edu/women-stem',
		contact_email: 'stem@yale.edu',
		status: 'approved',
		admin_comment: null,
		submitted_at: '2026-02-05T11:30:00.000Z',
	},
	{
		event_id: 3,
		org_id: 2,
		org_name: 'CT Science Center',
		title: 'Family Science Night',
		description: 'Interactive science experiments and demonstrations for the whole family.',
		start_datetime: '2026-04-05T17:00:00.000Z',
		end_datetime:   '2026-04-05T20:00:00.000Z',
		address: '250 Columbus Blvd',
		city: 'Hartford',
		county: 'Hartford',
		audience: 'Families',
		cost: '12.00',
		event_link: 'https://ctsci.org/family-night',
		contact_email: 'events@ctsci.org',
		status: 'pending',
		admin_comment: null,
		submitted_at: '2026-02-12T14:00:00.000Z',
	},
	{
		event_id: 4,
		org_id: 2,
		org_name: 'CT Science Center',
		title: 'Coding Bootcamp for Kids',
		description: 'Introduction to coding using Scratch and Python for elementary school students.',
		start_datetime: '2026-04-12T09:00:00.000Z',
		end_datetime:   '2026-04-12T12:00:00.000Z',
		address: '250 Columbus Blvd',
		city: 'Hartford',
		county: 'Hartford',
		audience: 'Ages 8-12',
		cost: '5.00',
		event_link: 'https://ctsci.org/kids-coding',
		contact_email: 'events@ctsci.org',
		status: 'denied',
		admin_comment: 'Missing age-appropriate safety information. Please add supervision details.',
		submitted_at: '2026-02-08T10:00:00.000Z',
	},
	{
		event_id: 5,
		org_id: 3,
		org_name: 'Wilbur Elementary School',
		title: 'STEM Career Fair',
		description: 'Local professionals showcase STEM career paths for elementary students.',
		start_datetime: '2026-03-28T09:00:00.000Z',
		end_datetime:   '2026-03-28T13:00:00.000Z',
		address: '45 School St',
		city: 'Middletown',
		county: 'Middlesex',
		audience: 'Elementary Students',
		cost: '0.00',
		event_link: null,
		contact_email: 'mfrank@wilbur.edu',
		status: 'pending',
		admin_comment: null,
		submitted_at: '2026-02-14T16:30:00.000Z',
	},
	{
		event_id: 6,
		org_id: 3,
		org_name: 'Wilbur Elementary School',
		title: 'Math Olympics Prep Session',
		description: 'Preparation workshop for the upcoming regional Math Olympics competition.',
		start_datetime: '2026-03-10T15:00:00.000Z',
		end_datetime:   '2026-03-10T17:00:00.000Z',
		address: '45 School St',
		city: 'Middletown',
		county: 'Middlesex',
		audience: 'Grades 3-5',
		cost: '0.00',
		event_link: null,
		contact_email: 'mfrank@wilbur.edu',
		status: 'approved',
		admin_comment: null,
		submitted_at: '2026-01-25T08:00:00.000Z',
	},

	// Viewer-submitted events (org_id: null)
	{
		event_id: 7,
		org_id: null,
		org_name: null,
		submitter_name: 'Dana Reyes',
		title: 'Backyard Astronomy Night',
		description: 'Community stargazing event open to all ages. Bring a blanket and look up! Hosted by a local amateur astronomer.',
		start_datetime: '2026-03-20T20:00:00.000Z',
		end_datetime:   '2026-03-20T22:30:00.000Z',
		address: '88 Hilltop Rd',
		city: 'Hamden',
		county: 'New Haven',
		audience: 'All Ages',
		cost: '0.00',
		event_link: null,
		contact_email: 'dreyes@gmail.com',
		status: 'pending',
		admin_comment: null,
		submitted_at: '2026-02-15T19:00:00.000Z',
	},
	{
		event_id: 8,
		org_id: null,
		org_name: null,
		submitter_name: 'Marcus Webb',
		title: '3D Printing Open House',
		description: 'Drop-in session at the local makerspace to try 3D printing and learn basic CAD design.',
		start_datetime: '2026-04-02T13:00:00.000Z',
		end_datetime:   '2026-04-02T16:00:00.000Z',
		address: '12 Canal St',
		city: 'New Haven',
		county: 'New Haven',
		audience: 'Ages 14+',
		cost: '5.00',
		event_link: 'https://newhavenmakerspace.org/events',
		contact_email: 'mwebb@newhavenmakerspace.org',
		status: 'approved',
		admin_comment: null,
		submitted_at: '2026-02-01T10:00:00.000Z',
	},
	{
		event_id: 9,
		org_id: null,
		org_name: null,
		submitter_name: 'Priya Nair',
		title: 'Introduction to Electronics for Teens',
		description: 'Teens learn to solder, read circuit diagrams, and build a simple LED gadget to take home.',
		start_datetime: '2026-04-18T10:00:00.000Z',
		end_datetime:   '2026-04-18T12:00:00.000Z',
		address: '300 Orange St',
		city: 'New Haven',
		county: 'New Haven',
		audience: 'Ages 13-17',
		cost: '10.00',
		event_link: null,
		contact_email: 'priya.nair@outlook.com',
		status: 'denied',
		admin_comment: 'Please provide details on safety supervision and material sourcing before resubmitting.',
		submitted_at: '2026-02-09T14:00:00.000Z',
	},
];
